AllCops:
  Exclude:
    - bin/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - spec/*
